//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public byte commentID { get; set; }
        public string message { get; set; }
        public byte masterID { get; set; }
        public byte requestID { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
