//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public byte requestID { get; set; }
        public System.DateTime startDate { get; set; }
        public string carType { get; set; }
        public string carModel { get; set; }
        public string problemDescription { get; set; }
        public string requestStatus { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public Nullable<byte> repairParts { get; set; }
        public Nullable<byte> masterID { get; set; }
        public byte clientID { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
